# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 492cd0bf0f9d93fac189073c2fd151692f941e01f2dcddfafe8e6231469fe7c8eb3d43f674f6fc36cd7538af9efc41488efefbe12f752f19146a5644d6948bec

test:
  secret_key_base: 0eb484975cdac09109da29811081b9bc2796156b39e72b6e456e518b54a83f62102b7a08a960d0fb261cad9ce49d1a07a03e065c0eb441da086241878987c3d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 78596f4023236e370323614dd917f913e9c58bca64f169207759494238fa8a89166d509557ed7285f92f2872da9fe6d3d7f7622640601c0c6753030fe2d10af9
